### PR TITLE
Adding chat-specific error handling

### PR DESCRIPTION
**Pull request by bogdanf**
Added a case to the existing `OpenAIError` to handle errors returned by the new 'chat' model.

### CODE REVIEW

**Comment by adamrushy** [comment]
This looks good overall @bogdanf please may you fix the conflicts? 🙏🏼

**Comment by bogdanf** [comment]
Done !

**Comment by julianschiavo** [comment]
I've been seeing frequent errors (not because of this framework—but because of OpenAI's terrible uptime!) which I suspect this might fix (I.e. handle better). Would love to see this get merged soon, thank you @bogdanf 😄

**Comment by bogdanf** [comment]
The conflicts from recent merges are now resolved.

**Pull request merged**
