### PR TITLE
Yet another `gpt-3.5-turbo` model implementation

### PR DESCRIPTION
**Pull request by bogdanf**
Did my own implementation in parallel with others. I like mine a little bit better, it uses generics to model the various responses coming from the the old endpoints and the new `chat` endpoint.

### CODE REVIEW

**Comment by underthestars-zhy** [comment]
When this will be merged?

**Comment by l0u1sg** [comment]
It would be great if this PR could be merged so that we could use the ``gpt-3.5-turbo`` model

**Comment by thesultanster** [comment]
Please let's merge this!

**Comment by pmstani** [comment]
It looks very good to me, I'm also in favor of merging this

**Comment by adamrushy** [comment]
Thank you @bogdanf for the contribution. Sorry for the delay - I wanted to run various tests on this :]

**Pull request merged**
