### PR TITLE
Add `usage` to `OpenAI` payload struct

### PR DESCRIPTION
**Pull request by eastriverlee**
Hi, I enjoyed working with your library. but I wanted to know how many tokens I've used,
so I made a very small change:
```swift
public struct OpenAI<T: Payload>: Codable {
    public let object: String
    public let model: String?
    public let choices: [T]
    public let usage: UsageResult
}

public struct UsageResult: Payload {
    public let prompt_tokens: Int
    public let completion_tokens: Int
    public let total_tokens: Int
}
```
This way, we can track tokens usage for `sendEdits`, `sendCompletion`, and `sendChats` without changing anything else.

### CODE REVIEW

**Comment by bogdanf** [comment]
I'd love to see this merged, but with better, swifter names for the members of `UsageResult`, like `promptTokens` instead of `prompt_tokens`.

**Comment by eastriverlee** [comment]
To get decoded by `JsonDecoder`, this is a must, since these are parameter names of the OpenAI's API result. If one wants to have more 'swifty' name, extension with computed property is possible, like:
```swift
extension OpenAI {
    var promptTokens: Int { prompt_tokens }
    ...
}
```
but I thought keeping changes to absolute minimum was more important.

**Comment by eastriverlee** [comment]
That's good to know! Honestly I did not know that.
In that case, I guess there is no reason to not change names.

I renamed properties and tested a new commit.

**Comment by bogdanf** [comment]
One more thing, `UsageResults` should not conform to `Payload` but to `Codable`. `Payload` is intended to model one of the `choices` in the `OpenAI` struct, not anything else.

**Comment by eastriverlee** [comment]
Make sense. I wondered why `Payload` exist and just went it 🤭 without thinking too much.

**Pull request merged**
